const juzhu = '居住人口'
const gongzuo = '工作人口'
const changzhu = '常住人口'
const keliu = '客流人口'
export const sex = '性别'
export const age = '年龄'
export const education = '学历'
export const marriage = '婚姻'
export const car = '车辆情况'
export const birth = '生育'
export const asset = '资产等级'
export const industry = '行业'

export const populations = [juzhu, gongzuo, changzhu, keliu]

const balance = '综合'
const weekday = '工作日'
const holiday = '节假日'

export const flows = [balance, weekday, holiday]

export const topType = {
  type1: 'top20居住地',
  type2: 'top20工作地',
  type3: 'top20活跃商圈',
  type4: 'top20商场偏好',
  type5: 'top20娱乐场所偏好'
}

export const custFlow = {
  [balance]: {
    index: 2259938,
    list: [
      { name: '00', value: 100686 },
      { name: '01', value: 74581 },
      { name: '02', value: 63024 },
      { name: '03', value: 58228 },
      { name: '04', value: 58613 },
      { name: '05', value: 85722 },
      { name: '06', value: 157212 },
      { name: '07', value: 251203 },
      { name: '08', value: 336689 },
      { name: '09', value: 305655 },
      { name: '10', value: 300636 },
      { name: '11', value: 313594 },
      { name: '12', value: 296338 },
      { name: '13', value: 282137 },
      { name: '14', value: 279652 },
      { name: '15', value: 289595 },
      { name: '16', value: 307189 },
      { name: '17', value: 357925 },
      { name: '18', value: 326349 },
      { name: '19', value: 290835 },
      { name: '20', value: 268299 },
      { name: '21', value: 228066 },
      { name: '22', value: 182033 },
      { name: '23', value: 131830 }
    ]
  },
  [weekday]: {
    index: 2306543,
    list: [
      { name: '00', value: 98143 },
      { name: '01', value: 72832 },
      { name: '02', value: 61901 },
      { name: '03', value: 57652 },
      { name: '04', value: 58180 },
      { name: '05', value: 85999 },
      { name: '06', value: 160672 },
      { name: '07', value: 262447 },
      { name: '08', value: 357559 },
      { name: '09', value: 309857 },
      { name: '10', value: 302076 },
      { name: '11', value: 319291 },
      { name: '12', value: 301041 },
      { name: '13', value: 284913 },
      { name: '14', value: 282660 },
      { name: '15', value: 293403 },
      { name: '16', value: 312407 },
      { name: '17', value: 373784 },
      { name: '18', value: 335576 },
      { name: '19', value: 292971 },
      { name: '20', value: 269771 },
      { name: '21', value: 228843 },
      { name: '22', value: 182383 },
      { name: '23', value: 131477 }
    ]
  },
  [holiday]: {
    index: 2162139,
    list: [
      { name: '00', value: 106170 },
      { name: '01', value: 78340 },
      { name: '02', value: 65512 },
      { name: '03', value: 59560 },
      { name: '04', value: 59531 },
      { name: '05', value: 85224 },
      { name: '06', value: 149974 },
      { name: '07', value: 227658 },
      { name: '08', value: 293060 },
      { name: '09', value: 297020 },
      { name: '10', value: 297691 },
      { name: '11', value: 301742 },
      { name: '12', value: 286551 },
      { name: '13', value: 276389 },
      { name: '14', value: 273449 },
      { name: '15', value: 281746 },
      { name: '16', value: 296346 },
      { name: '17', value: 324828 },
      { name: '18', value: 307136 },
      { name: '19', value: 286543 },
      { name: '20', value: 265296 },
      { name: '21', value: 226501 },
      { name: '22', value: 181361 },
      { name: '23', value: 132747 }
    ]
  }
}
export const groupPortrait = {
  [juzhu]: {
    index: 518837,
    ['性别']: [
      { name: '男', value: 0.5208 },
      { name: '女', value: 0.4792 }
    ],
    ['年龄']: [
      { name: '19-24', value: 0.1328 },
      { name: '25-34', value: 0.3399 },
      { name: '35-44', value: 0.2695 },
      { name: '45-54', value: 0.1332 },
      { name: '＞=55', value: 0.1245 }
    ],
    ['学历']: [
      { name: '初高中', value: 0.0001 },
      { name: '专科', value: 0.0085 },
      { name: '硕士', value: 0.008 },
      { name: '本科', value: 0.0418 },
      { name: '博士', value: 0.0008 },
      { name: '未知', value: 0.9408 }
    ],
    ['婚姻']: [
      { name: '未婚', value: 0.1684 },
      { name: '已婚', value: 0.8316 }
    ],
    ['车辆情况']: [
      { name: '无车', value: 0.7958 },
      { name: '有车', value: 0.2042 }
    ],
    ['生育']: [
      { name: '未育', value: 0.1726 },
      { name: '已育', value: 0.8274 }
    ],
    ['资产等级']: [
      { name: '超级富豪', value: 0 },
      { name: '富豪', value: 0.0154 },
      { name: '中产', value: 0.3554 },
      { name: '工薪一族', value: 0.6292 }
    ],
    ['行业']: [
      { name: '医疗卫生', value: 0.1466 },
      { name: '购物服务', value: 0.1328 },
      { name: '酒店服务', value: 0.0995 },
      { name: '教育', value: 0.0979 },
      { name: '生活服务', value: 0.0929 },
      { name: '冶金化工', value: 0.0631 },
      { name: '机械电子', value: 0.0582 },
      { name: '公共事业服务', value: 0.0529 },
      { name: '商业贸易', value: 0.0474 },
      { name: '网络科技', value: 0.0423 },
      { name: '房地产', value: 0.0287 },
      { name: '银行', value: 0.0286 },
      { name: '餐饮服务', value: 0.0281 },
      { name: '汽车服务', value: 0.0273 },
      { name: '广告装饰', value: 0.0154 },
      { name: '培训', value: 0.0078 },
      { name: '客运服务', value: 0.0065 },
      { name: '能源矿产', value: 0.0059 },
      { name: '科研', value: 0.0051 },
      { name: '快递/配送服务', value: 0.0034 },
      { name: '金融', value: 0.0029 },
      { name: '传媒', value: 0.0029 },
      { name: '货运服务', value: 0.0014 },
      { name: '保险', value: 0.0011 },
      { name: '农林渔牧', value: 0.001 },
      { name: '证券', value: 0.0006 }
    ]
  },
  [gongzuo]: {
    index: 618837,
    [sex]: [
      { name: '男', value: 0.5368 },
      { name: '女', value: 0.4632 }
    ],
    [age]: [
      { name: '19-24', value: 0.1453 },
      { name: '25-34', value: 0.3661 },
      { name: '35-44', value: 0.2847 },
      { name: '45-54', value: 0.1234 },
      { name: '＞=55', value: 0.0805 }
    ],
    [education]: [
      { name: '初高中', value: 0.0001 },
      { name: '专科', value: 0.0103 },
      { name: '硕士', value: 0.0091 },
      { name: '本科', value: 0.0473 },
      { name: '博士', value: 0.0009 },
      { name: '未知', value: 0.9323 }
    ],
    [marriage]: [
      { name: '未婚', value: 0.1709 },
      { name: '已婚', value: 0.8291 }
    ],
    [car]: [
      { name: '无车', value: 0.783 },
      { name: '有车', value: 0.217 }
    ],
    [birth]: [
      { name: '未育', value: 0.1755 },
      { name: '已育', value: 0.8245 }
    ],
    [asset]: [
      { name: '超级富豪', value: 0 },
      { name: '富豪', value: 0.0215 },
      { name: '中产', value: 0.3491 },
      { name: '工薪一族', value: 0.6294 }
    ],
    [industry]: [
      { name: '医疗卫生', value: 0.1808 },
      { name: '购物服务', value: 0.134 },
      { name: '酒店服务', value: 0.1045 },
      { name: '生活服务', value: 0.099 },
      { name: '教育', value: 0.0794 },
      { name: '公共事业服务', value: 0.0697 },
      { name: '银行', value: 0.0451 },
      { name: '冶金化工', value: 0.0439 },
      { name: '商业贸易', value: 0.0411 },
      { name: '机械电子', value: 0.0393 },
      { name: '网络科技', value: 0.0347 },
      { name: '餐饮服务', value: 0.0291 },
      { name: '汽车服务', value: 0.0251 },
      { name: '房地产', value: 0.0251 },
      { name: '广告装饰', value: 0.0148 },
      { name: '客运服务', value: 0.008 },
      { name: '培训', value: 0.0075 },
      { name: '快递/配送服务', value: 0.0039 },
      { name: '能源矿产', value: 0.0037 },
      { name: '金融', value: 0.0031 },
      { name: '科研', value: 0.0028 },
      { name: '货运服务', value: 0.0017 },
      { name: '传媒', value: 0.0014 },
      { name: '保险', value: 0.001 },
      { name: '农林渔牧', value: 0.0007 },
      { name: '证券', value: 0.0005 }
    ]
  },
  [changzhu]: {
    index: 1104826,
    [sex]: [
      { name: '男', value: 0.5297 },
      { name: '女', value: 0.4703 }
    ],
    [age]: [
      { name: '19-24', value: 0.1397 },
      { name: '25-34', value: 0.3543 },
      { name: '35-44', value: 0.2776 },
      { name: '45-54', value: 0.1279 },
      { name: '＞=55', value: 0.1005 }
    ],
    [education]: [
      { name: '初高中', value: 0.0001 },
      { name: '专科', value: 0.0094 },
      { name: '硕士', value: 0.0086 },
      { name: '本科', value: 0.0449 },
      { name: '博士', value: 0.0009 },
      { name: '未知', value: 0.9361 }
    ],
    [marriage]: [
      { name: '未婚', value: 0.1698 },
      { name: '已婚', value: 0.8302 }
    ],
    [car]: [
      { name: '无车', value: 0.7888 },
      { name: '有车', value: 0.2112 }
    ],
    [birth]: [
      { name: '未育', value: 0.1743 },
      { name: '已育', value: 0.8257 }
    ],
    [asset]: [
      { name: '超级富豪', value: 0 },
      { name: '富豪', value: 0.0188 },
      { name: '中产', value: 0.3524 },
      { name: '工薪一族', value: 0.6288 }
    ],
    [industry]: [
      { name: '医疗卫生', value: 0.1651 },
      { name: '购物服务', value: 0.1332 },
      { name: '酒店服务', value: 0.1019 },
      { name: '生活服务', value: 0.096 },
      { name: '教育', value: 0.0882 },
      { name: '公共事业服务', value: 0.062 },
      { name: '冶金化工', value: 0.0529 },
      { name: '机械电子', value: 0.048 },
      { name: '商业贸易', value: 0.0441 },
      { name: '网络科技', value: 0.0383 },
      { name: '银行', value: 0.0375 },
      { name: '餐饮服务', value: 0.0285 },
      { name: '房地产', value: 0.0268 },
      { name: '汽车服务', value: 0.0261 },
      { name: '广告装饰', value: 0.0151 },
      { name: '培训', value: 0.0076 },
      { name: '客运服务', value: 0.0073 },
      { name: '能源矿产', value: 0.0047 },
      { name: '科研', value: 0.0039 },
      { name: '快递/配送服务', value: 0.0037 },
      { name: '金融', value: 0.003 },
      { name: '传媒', value: 0.0021 },
      { name: '货运服务', value: 0.0015 },
      { name: '保险', value: 0.001 },
      { name: '农林渔牧', value: 0.0009 },
      { name: '证券', value: 0.0006 }
    ]
  },
  [keliu]: {
    index: 1104826,
    [sex]: [
      { name: '男', value: 0.5991 },
      { name: '女', value: 0.4009 }
    ],
    [age]: [
      { name: '19-24', value: 0.0974 },
      { name: '25-34', value: 0.269 },
      { name: '35-44', value: 0.2982 },
      { name: '45-54', value: 0.1952 },
      { name: '＞=55', value: 0.1401 }
    ],
    [education]: [
      { name: '专科', value: 0.008 },
      { name: '硕士', value: 0.0084 },
      { name: '本科', value: 0.0363 },
      { name: '博士', value: 0.0016 },
      { name: '未知', value: 0.9457 }
    ],
    [marriage]: [
      { name: '未婚', value: 0.1228 },
      { name: '已婚', value: 0.8772 }
    ],
    [car]: [
      { name: '无车', value: 0.7819 },
      { name: '有车', value: 0.2181 }
    ],
    [birth]: [
      { name: '未育', value: 0.1255 },
      { name: '已育', value: 0.8745 }
    ],
    [asset]: [
      { name: '超级富豪', value: 0.0005 },
      { name: '富豪', value: 0.0397 },
      { name: '中产', value: 0.5316 },
      { name: '工薪一族', value: 0.4283 }
    ],
    [industry]: [
      { name: '医疗卫生', value: 0.1252 },
      { name: '购物服务', value: 0.1055 },
      { name: '生活服务', value: 0.0915 },
      { name: '酒店服务', value: 0.0784 },
      { name: '教育', value: 0.0752 },
      { name: '冶金化工', value: 0.0628 },
      { name: '机械电子', value: 0.0605 },
      { name: '公共事业服务', value: 0.0535 },
      { name: '商业贸易', value: 0.0458 },
      { name: '网络科技', value: 0.045 },
      { name: '快递/配送服务', value: 0.0404 },
      { name: '房地产', value: 0.0355 },
      { name: '客运服务', value: 0.0274 },
      { name: '餐饮服务', value: 0.0268 },
      { name: '银行', value: 0.0264 },
      { name: '汽车服务', value: 0.0254 },
      { name: '广告装饰', value: 0.0168 },
      { name: '培训', value: 0.0098 },
      { name: '能源矿产', value: 0.0092 },
      { name: '货运服务', value: 0.009 },
      { name: '科研', value: 0.0076 },
      { name: '金融', value: 0.0059 },
      { name: '传媒', value: 0.0055 },
      { name: '保险', value: 0.0039 },
      { name: '农林渔牧', value: 0.0036 },
      { name: '证券', value: 0.0031 }
    ]
  }
}

export const hotRegion = [
  { region: '常青藤·小城', type: juzhu, top: topType.type1, value: 13173 },
  { region: '波波城', type: juzhu, top: topType.type1, value: 12736 },
  { region: '江南一品', type: juzhu, top: topType.type1, value: 10240 },
  { region: '东部新城', type: juzhu, top: topType.type1, value: 10157 },
  { region: '锦苑社区', type: juzhu, top: topType.type1, value: 9659 },
  { region: '福明家园三期', type: juzhu, top: topType.type1, value: 8247 },
  { region: '华光城', type: juzhu, top: topType.type1, value: 8090 },
  { region: '书香景苑北区1期', type: juzhu, top: topType.type1, value: 7977 },
  { region: '明东社区', type: juzhu, top: topType.type1, value: 7694 },
  { region: '陆嘉家园', type: juzhu, top: topType.type1, value: 7137 },
  { region: '园丁社区', type: juzhu, top: topType.type1, value: 6978 },
  { region: '涨浦景苑', type: juzhu, top: topType.type1, value: 6705 },
  { region: '中兴社区', type: juzhu, top: topType.type1, value: 6611 },
  { region: '莘香雅苑', type: juzhu, top: topType.type1, value: 6518 },
  { region: '涨馨苑', type: juzhu, top: topType.type1, value: 6032 },
  { region: '五和苑', type: juzhu, top: topType.type1, value: 6020 },
  { region: '安居幸福苑', type: juzhu, top: topType.type1, value: 5701 },
  { region: '书香景苑南区二期', type: juzhu, top: topType.type1, value: 5583 },
  { region: '江南春晓', type: juzhu, top: topType.type1, value: 5275 },
  { region: '太古城小区', type: juzhu, top: topType.type1, value: 5225 },
  { region: '东部新城', type: juzhu, top: topType.type2, value: 10343 },
  { region: '宁波市医疗中心李惠利医院东部院区', type: juzhu, top: topType.type2, value: 3424 },
  { region: '世纪东方广场', type: juzhu, top: topType.type2, value: 3313 },
  { region: '宏泰广场', type: juzhu, top: topType.type2, value: 3113 },
  { region: '宁波新材料(国际)创新中心', type: juzhu, top: topType.type2, value: 2908 },
  { region: '宁波研发园B区', type: juzhu, top: topType.type2, value: 2736 },
  { region: '阪急百货', type: juzhu, top: topType.type2, value: 2518 },
  { region: '国贸中心领寓', type: juzhu, top: topType.type2, value: 2461 },
  { region: '新天地东区', type: juzhu, top: topType.type2, value: 2260 },
  { region: '宁波研发园南区', type: juzhu, top: topType.type2, value: 2123 },
  { region: '泰富广场', type: juzhu, top: topType.type2, value: 2006 },
  { region: '宁波大学附属人民医院-南区', type: juzhu, top: topType.type2, value: 1804 },
  { region: '宁波银行总行大厦', type: juzhu, top: topType.type2, value: 1751 },
  { region: '韵升科技工业园', type: juzhu, top: topType.type2, value: 1732 },
  { region: '宁波国际金融服务中心', type: juzhu, top: topType.type2, value: 1732 },
  { region: '东部银泰城', type: juzhu, top: topType.type2, value: 1568 },
  { region: '港隆广场', type: juzhu, top: topType.type2, value: 1454 },
  { region: '宁波市第六医院', type: juzhu, top: topType.type2, value: 1320 },
  { region: '宁波市人民政府', type: juzhu, top: topType.type2, value: 1299 },
  { region: '宁波环球航运广场', type: juzhu, top: topType.type2, value: 1186 },
  { region: '西门', type: juzhu, top: topType.type3, value: 270436 },
  { region: '南门', type: juzhu, top: topType.type3, value: 239332 },
  { region: '百丈', type: juzhu, top: topType.type3, value: 58444 },
  { region: '福明', type: juzhu, top: topType.type3, value: 51714 },
  { region: '桑田路', type: juzhu, top: topType.type3, value: 33992 },
  { region: '高新区', type: juzhu, top: topType.type3, value: 30759 },
  { region: '南门', type: juzhu, top: topType.type3, value: 21912 },
  { region: '中河', type: juzhu, top: topType.type3, value: 11878 },
  { region: '明楼', type: juzhu, top: topType.type3, value: 10489 },
  { region: '庄市社区', type: juzhu, top: topType.type3, value: 8494 },
  { region: '首南', type: juzhu, top: topType.type3, value: 7903 },
  { region: '下应', type: juzhu, top: topType.type3, value: 6562 },
  { region: '梅墟', type: juzhu, top: topType.type3, value: 6522 },
  { region: '东胜', type: juzhu, top: topType.type3, value: 5825 },
  { region: '东柳', type: juzhu, top: topType.type3, value: 5662 },
  { region: '庄市', type: juzhu, top: topType.type3, value: 5257 },
  { region: '五乡', type: juzhu, top: topType.type3, value: 4102 },
  { region: '钟公庙', type: juzhu, top: topType.type3, value: 3882 },
  { region: '舟山群岛新区', type: juzhu, top: topType.type3, value: 3459 },
  { region: '环城北路', type: juzhu, top: topType.type3, value: 2817 },
  { region: '世纪东方广场', type: juzhu, top: topType.type4, value: 57222 },
  { region: '宁波天一广场', type: juzhu, top: topType.type4, value: 45894 },
  { region: '宏泰广场', type: juzhu, top: topType.type4, value: 42339 },
  { region: '东部银泰城', type: juzhu, top: topType.type4, value: 40780 },
  { region: '阪急百货', type: juzhu, top: topType.type4, value: 33951 },
  { region: '港隆广场', type: juzhu, top: topType.type4, value: 25434 },
  { region: '万达广场(鄞州店)', type: juzhu, top: topType.type4, value: 20229 },
  { region: '宁波鄞州印象城', type: juzhu, top: topType.type4, value: 19285 },
  { region: '宁波来福士广场', type: juzhu, top: topType.type4, value: 18968 },
  { region: '银泰百货(江东店)', type: juzhu, top: topType.type4, value: 18919 },
  { region: '万象城', type: juzhu, top: topType.type4, value: 17414 },
  { region: '宁波鄞州宝龙广场', type: juzhu, top: topType.type4, value: 12437 },
  { region: '天伦时代广场', type: juzhu, top: topType.type4, value: 12110 },
  { region: '金沙码头奥莱公园', type: juzhu, top: topType.type4, value: 10736 },
  { region: '国际购物中心', type: juzhu, top: topType.type4, value: 10419 },
  { region: '和义大道购物中心', type: juzhu, top: topType.type4, value: 9879 },
  { region: '宁波集盒MR.BOX', type: juzhu, top: topType.type4, value: 9359 },
  { region: '银泰百货(天一店)', type: juzhu, top: topType.type4, value: 8923 },
  { region: '亚细亚75mall(宁波店)', type: juzhu, top: topType.type4, value: 8405 },
  { region: '杉井奥特莱斯广场·宁波', type: juzhu, top: topType.type4, value: 8397 },
  { region: 'SFC上影影城(宁波店)', type: juzhu, top: topType.type5, value: 16090 },
  { region: 'AGToys漫玩', type: juzhu, top: topType.type5, value: 15046 },
  { region: '乐酷KTV(宏泰广场)', type: juzhu, top: topType.type5, value: 12604 },
  { region: '罗蒙环球乐园', type: juzhu, top: topType.type5, value: 11457 },
  { region: '魅KTV(宁波高新宝龙广场店)', type: juzhu, top: topType.type5, value: 8313 },
  { region: '北极王国冰雪世界(东部银泰城店)', type: juzhu, top: topType.type5, value: 8071 },
  { region: '宁波大光明主题影院(桑田路店)', type: juzhu, top: topType.type5, value: 7719 },
  { region: '可可天空农场(东部新城银泰城店)', type: juzhu, top: topType.type5, value: 7716 },
  { region: '阿正点播影院(城隍庙店)', type: juzhu, top: topType.type5, value: 7583 },
  { region: '中影国际影城(来福士店)', type: juzhu, top: topType.type5, value: 7225 },
  { region: 'TZ House音乐现场(宁波来福士店)', type: juzhu, top: topType.type5, value: 6766 },
  { region: '天伦·极度沸点KTV(朝晖路店)', type: juzhu, top: topType.type5, value: 6460 },
  { region: '宁波恒鼎国际商务会所', type: juzhu, top: topType.type5, value: 6235 },
  { region: '四合网苑(东柳店)', type: juzhu, top: topType.type5, value: 5694 },
  { region: '江东一页时尚KTV', type: juzhu, top: topType.type5, value: 5627 },
  { region: '涌上·音悦汇KTV(开明街店)', type: juzhu, top: topType.type5, value: 5618 },
  { region: 'Me land(东部新城银泰店)', type: juzhu, top: topType.type5, value: 5501 },
  { region: '百老汇影城(印象城)', type: juzhu, top: topType.type5, value: 5223 },
  { region: 'AGTOYS漫玩(世纪东方店)', type: juzhu, top: topType.type5, value: 5199 },
  { region: '泛尼尼儿童亲子乐园(文化广场店)', type: juzhu, top: topType.type5, value: 5037 },
  { region: '东部新城', type: gongzuo, top: topType.type1, value: 3128 },
  { region: '江南一品', type: gongzuo, top: topType.type1, value: 2862 },
  { region: '波波城', type: gongzuo, top: topType.type1, value: 2738 },
  { region: '常青藤·小城', type: gongzuo, top: topType.type1, value: 2673 },
  { region: '莘香雅苑', type: gongzuo, top: topType.type1, value: 2551 },
  { region: '福明家园三期', type: gongzuo, top: topType.type1, value: 2505 },
  { region: '书香景苑北区1期', type: gongzuo, top: topType.type1, value: 2367 },
  { region: '锦苑社区', type: gongzuo, top: topType.type1, value: 2361 },
  { region: '陆嘉家园', type: gongzuo, top: topType.type1, value: 1964 },
  { region: '华光城', type: gongzuo, top: topType.type1, value: 1884 },
  { region: '书香景苑南区二期', type: gongzuo, top: topType.type1, value: 1811 },
  { region: '涨浦景苑', type: gongzuo, top: topType.type1, value: 1704 },
  { region: '碧水和城', type: gongzuo, top: topType.type1, value: 1621 },
  { region: '和美城', type: gongzuo, top: topType.type1, value: 1597 },
  { region: '新天地西区', type: gongzuo, top: topType.type1, value: 1496 },
  { region: '东方丽都', type: gongzuo, top: topType.type1, value: 1466 },
  { region: '恒大·城市之光', type: gongzuo, top: topType.type1, value: 1404 },
  { region: '园丁社区', type: gongzuo, top: topType.type1, value: 1380 },
  { region: '明东社区', type: gongzuo, top: topType.type1, value: 1368 },
  { region: '中兴社区', type: gongzuo, top: topType.type1, value: 1361 },
  { region: '东部新城', type: gongzuo, top: topType.type2, value: 42936 },
  { region: '宁波市医疗中心李惠利医院东部院区', type: gongzuo, top: topType.type2, value: 19663 },
  { region: '宏泰广场', type: gongzuo, top: topType.type2, value: 13811 },
  { region: '韵升科技工业园', type: gongzuo, top: topType.type2, value: 11978 },
  { region: '阪急百货', type: gongzuo, top: topType.type2, value: 11360 },
  { region: '宁波市第六医院', type: gongzuo, top: topType.type2, value: 11328 },
  { region: '国贸中心领寓', type: gongzuo, top: topType.type2, value: 10187 },
  { region: '世纪东方广场', type: gongzuo, top: topType.type2, value: 10100 },
  { region: '宁波国际金融服务中心', type: gongzuo, top: topType.type2, value: 7659 },
  { region: '宁波市人民政府', type: gongzuo, top: topType.type2, value: 7625 },
  { region: '新天地东区', type: gongzuo, top: topType.type2, value: 7609 },
  { region: '东部银泰城', type: gongzuo, top: topType.type2, value: 7533 },
  { region: '宁波银行总行大厦', type: gongzuo, top: topType.type2, value: 6887 },
  { region: '泰富广场', type: gongzuo, top: topType.type2, value: 6379 },
  { region: '宁波环球航运广场', type: gongzuo, top: topType.type2, value: 5890 },
  { region: '宁波国际贸易展览中心', type: gongzuo, top: topType.type2, value: 5788 },
  { region: '中银大厦', type: gongzuo, top: topType.type2, value: 4674 },
  { region: '宁波文化广场', type: gongzuo, top: topType.type2, value: 4490 },
  { region: '世界中华宁波总商会广场', type: gongzuo, top: topType.type2, value: 4250 },
  { region: '银晨国际商务中心', type: gongzuo, top: topType.type2, value: 4168 },
  { region: '西门', type: gongzuo, top: topType.type3, value: 296425 },
  { region: '南门', type: gongzuo, top: topType.type3, value: 278246 },
  { region: '福明', type: gongzuo, top: topType.type3, value: 97214 },
  { region: '高新区', type: gongzuo, top: topType.type3, value: 95534 },
  { region: '百丈', type: gongzuo, top: topType.type3, value: 40154 },
  { region: '桑田路', type: gongzuo, top: topType.type3, value: 35922 },
  { region: '南门', type: gongzuo, top: topType.type3, value: 22977 },
  { region: '中河', type: gongzuo, top: topType.type3, value: 18088 },
  { region: '明楼', type: gongzuo, top: topType.type3, value: 15858 },
  { region: '庄市社区', type: gongzuo, top: topType.type3, value: 15563 },
  { region: '东柳', type: gongzuo, top: topType.type3, value: 13237 },
  { region: '梅墟', type: gongzuo, top: topType.type3, value: 7380 },
  { region: '首南', type: gongzuo, top: topType.type3, value: 7287 },
  { region: '下应', type: gongzuo, top: topType.type3, value: 7156 },
  { region: '钟公庙', type: gongzuo, top: topType.type3, value: 6925 },
  { region: '红莲', type: gongzuo, top: topType.type3, value: 5761 },
  { region: '望春', type: gongzuo, top: topType.type3, value: 5606 },
  { region: '环城北路', type: gongzuo, top: topType.type3, value: 5034 },
  { region: '环城西路北段', type: gongzuo, top: topType.type3, value: 4791 },
  { region: '庄市', type: gongzuo, top: topType.type3, value: 4777 },
  { region: '世纪东方广场', type: gongzuo, top: topType.type4, value: 61073 },
  { region: '宁波天一广场', type: gongzuo, top: topType.type4, value: 59162 },
  { region: '宏泰广场', type: gongzuo, top: topType.type4, value: 56243 },
  { region: '东部银泰城', type: gongzuo, top: topType.type4, value: 46931 },
  { region: '阪急百货', type: gongzuo, top: topType.type4, value: 43869 },
  { region: '万达广场(鄞州店)', type: gongzuo, top: topType.type4, value: 32075 },
  { region: '宁波鄞州印象城', type: gongzuo, top: topType.type4, value: 29275 },
  { region: '宁波来福士广场', type: gongzuo, top: topType.type4, value: 24061 },
  { region: '万象城', type: gongzuo, top: topType.type4, value: 23769 },
  { region: '港隆广场', type: gongzuo, top: topType.type4, value: 23504 },
  { region: '宁波鄞州宝龙广场', type: gongzuo, top: topType.type4, value: 19296 },
  { region: '银泰百货(江东店)', type: gongzuo, top: topType.type4, value: 17601 },
  { region: '金沙码头奥莱公园', type: gongzuo, top: topType.type4, value: 13372 },
  { region: '杉井奥特莱斯广场·宁波', type: gongzuo, top: topType.type4, value: 13022 },
  { region: '国际购物中心', type: gongzuo, top: topType.type4, value: 12780 },
  { region: '天伦时代广场', type: gongzuo, top: topType.type4, value: 12729 },
  { region: '和义大道购物中心', type: gongzuo, top: topType.type4, value: 12192 },
  { region: '万达广场(江北店)', type: gongzuo, top: topType.type4, value: 12048 },
  { region: '环球银泰城', type: gongzuo, top: topType.type4, value: 11910 },
  { region: '滨江商业广场', type: gongzuo, top: topType.type4, value: 11575 },
  { region: '罗蒙环球乐园', type: gongzuo, top: topType.type5, value: 18585 },
  { region: 'AGToys漫玩', type: gongzuo, top: topType.type5, value: 16934 },
  { region: 'SFC上影影城(宁波店)', type: gongzuo, top: topType.type5, value: 15067 },
  { region: '乐酷KTV(宏泰广场)', type: gongzuo, top: topType.type5, value: 14347 },
  { region: '阿正点播影院(城隍庙店)', type: gongzuo, top: topType.type5, value: 10742 },
  { region: '百老汇影城(印象城)', type: gongzuo, top: topType.type5, value: 9659 },
  { region: '中影国际影城(来福士店)', type: gongzuo, top: topType.type5, value: 8909 },
  { region: '北极王国冰雪世界(东部银泰城店)', type: gongzuo, top: topType.type5, value: 8567 },
  { region: 'TZ House音乐现场(宁波来福士店)', type: gongzuo, top: topType.type5, value: 8104 },
  { region: '可可天空农场(东部新城银泰城店)', type: gongzuo, top: topType.type5, value: 8041 },
  { region: '魅KTV(宁波高新宝龙广场店)', type: gongzuo, top: topType.type5, value: 7717 },
  { region: '涌上·音悦汇KTV(开明街店)', type: gongzuo, top: topType.type5, value: 7371 },
  { region: '宁波大剧院', type: gongzuo, top: topType.type5, value: 7019 },
  { region: '自由人影城(宁波亚细亚CINITY店)', type: gongzuo, top: topType.type5, value: 6876 },
  { region: '天伦·极度沸点KTV(朝晖路店)', type: gongzuo, top: topType.type5, value: 6822 },
  { region: '宁波恒鼎国际商务会所', type: gongzuo, top: topType.type5, value: 5993 },
  { region: '屋有岛·星空密室(鄞州印象城店)', type: gongzuo, top: topType.type5, value: 5939 },
  { region: '四合网苑(东柳店)', type: gongzuo, top: topType.type5, value: 5704 },
  { region: '泛尼尼儿童亲子乐园(文化广场店)', type: gongzuo, top: topType.type5, value: 5636 },
  { region: 'Me land(东部新城银泰店)', type: gongzuo, top: topType.type5, value: 5603 },
  { region: '常青藤·小城', type: changzhu, top: topType.type1, value: 15799 },
  { region: '波波城', type: changzhu, top: topType.type1, value: 15428 },
  { region: '东部新城', type: changzhu, top: topType.type1, value: 13089 },
  { region: '江南一品', type: changzhu, top: topType.type1, value: 13023 },
  { region: '锦苑社区', type: changzhu, top: topType.type1, value: 11954 },
  { region: '福明家园三期', type: changzhu, top: topType.type1, value: 10734 },
  { region: '书香景苑北区1期', type: changzhu, top: topType.type1, value: 10324 },
  { region: '华光城', type: changzhu, top: topType.type1, value: 9912 },
  { region: '陆嘉家园', type: changzhu, top: topType.type1, value: 9085 },
  { region: '莘香雅苑', type: changzhu, top: topType.type1, value: 9047 },
  { region: '明东社区', type: changzhu, top: topType.type1, value: 9026 },
  { region: '涨浦景苑', type: changzhu, top: topType.type1, value: 8402 },
  { region: '园丁社区', type: changzhu, top: topType.type1, value: 8332 },
  { region: '中兴社区', type: changzhu, top: topType.type1, value: 7952 },
  { region: '书香景苑南区二期', type: changzhu, top: topType.type1, value: 7388 },
  { region: '五和苑', type: changzhu, top: topType.type1, value: 7356 },
  { region: '涨馨苑', type: changzhu, top: topType.type1, value: 7343 },
  { region: '安居幸福苑', type: changzhu, top: topType.type1, value: 6815 },
  { region: '碧水和城', type: changzhu, top: topType.type1, value: 6699 },
  { region: '和美城', type: changzhu, top: topType.type1, value: 6572 },
  { region: '东部新城', type: changzhu, top: topType.type2, value: 53028 },
  { region: '宁波市医疗中心李惠利医院东部院区', type: changzhu, top: topType.type2, value: 23070 },
  { region: '宏泰广场', type: changzhu, top: topType.type2, value: 16888 },
  { region: '阪急百货', type: changzhu, top: topType.type2, value: 13848 },
  { region: '韵升科技工业园', type: changzhu, top: topType.type2, value: 13435 },
  { region: '世纪东方广场', type: changzhu, top: topType.type2, value: 13402 },
  { region: '国贸中心领寓', type: changzhu, top: topType.type2, value: 12635 },
  { region: '宁波市第六医院', type: changzhu, top: topType.type2, value: 12631 },
  { region: '新天地东区', type: changzhu, top: topType.type2, value: 9821 },
  { region: '宁波国际金融服务中心', type: changzhu, top: topType.type2, value: 9384 },
  { region: '东部银泰城', type: changzhu, top: topType.type2, value: 9013 },
  { region: '宁波市人民政府', type: changzhu, top: topType.type2, value: 8925 },
  { region: '宁波银行总行大厦', type: changzhu, top: topType.type2, value: 8639 },
  { region: '泰富广场', type: changzhu, top: topType.type2, value: 8383 },
  { region: '宁波环球航运广场', type: changzhu, top: topType.type2, value: 7075 },
  { region: '宁波国际贸易展览中心', type: changzhu, top: topType.type2, value: 6808 },
  { region: '宁波文化广场', type: changzhu, top: topType.type2, value: 5534 },
  { region: '中银大厦', type: changzhu, top: topType.type2, value: 5481 },
  { region: '银晨国际商务中心', type: changzhu, top: topType.type2, value: 5116 },
  { region: '世界中华宁波总商会广场', type: changzhu, top: topType.type2, value: 5042 },
  { region: '西门', type: changzhu, top: topType.type3, value: 564712 },
  { region: '南门', type: changzhu, top: topType.type3, value: 515650 },
  { region: '福明', type: changzhu, top: topType.type3, value: 148540 },
  { region: '高新区', type: changzhu, top: topType.type3, value: 126181 },
  { region: '百丈', type: changzhu, top: topType.type3, value: 97992 },
  { region: '桑田路', type: changzhu, top: topType.type3, value: 69583 },
  { region: '南门', type: changzhu, top: topType.type3, value: 44785 },
  { region: '中河', type: changzhu, top: topType.type3, value: 29885 },
  { region: '明楼', type: changzhu, top: topType.type3, value: 26268 },
  { region: '庄市社区', type: changzhu, top: topType.type3, value: 24022 },
  { region: '东柳', type: changzhu, top: topType.type3, value: 18848 },
  { region: '首南', type: changzhu, top: topType.type3, value: 15171 },
  { region: '梅墟', type: changzhu, top: topType.type3, value: 13809 },
  { region: '下应', type: changzhu, top: topType.type3, value: 13708 },
  { region: '钟公庙', type: changzhu, top: topType.type3, value: 10805 },
  { region: '庄市', type: changzhu, top: topType.type3, value: 10008 },
  { region: '东胜', type: changzhu, top: topType.type3, value: 8907 },
  { region: '五乡', type: changzhu, top: topType.type3, value: 8829 },
  { region: '红莲', type: changzhu, top: topType.type3, value: 8464 },
  { region: '望春', type: changzhu, top: topType.type3, value: 8116 },
  { region: '世纪东方广场', type: changzhu, top: topType.type4, value: 117968 },
  { region: '宁波天一广场', type: changzhu, top: topType.type4, value: 104784 },
  { region: '宏泰广场', type: changzhu, top: topType.type4, value: 98349 },
  { region: '东部银泰城', type: changzhu, top: topType.type4, value: 87489 },
  { region: '阪急百货', type: changzhu, top: topType.type4, value: 77600 },
  { region: '万达广场(鄞州店)', type: changzhu, top: topType.type4, value: 52194 },
  { region: '港隆广场', type: changzhu, top: topType.type4, value: 48842 },
  { region: '宁波鄞州印象城', type: changzhu, top: topType.type4, value: 48500 },
  { region: '宁波来福士广场', type: changzhu, top: topType.type4, value: 42942 },
  { region: '万象城', type: changzhu, top: topType.type4, value: 41135 },
  { region: '银泰百货(江东店)', type: changzhu, top: topType.type4, value: 36487 },
  { region: '宁波鄞州宝龙广场', type: changzhu, top: topType.type4, value: 31696 },
  { region: '天伦时代广场', type: changzhu, top: topType.type4, value: 24897 },
  { region: '金沙码头奥莱公园', type: changzhu, top: topType.type4, value: 24112 },
  { region: '国际购物中心', type: changzhu, top: topType.type4, value: 23181 },
  { region: '和义大道购物中心', type: changzhu, top: topType.type4, value: 22173 },
  { region: '杉井奥特莱斯广场·宁波', type: changzhu, top: topType.type4, value: 21458 },
  { region: '银泰百货(天一店)', type: changzhu, top: topType.type4, value: 20371 },
  { region: '亚细亚75mall(宁波店)', type: changzhu, top: topType.type4, value: 20080 },
  { region: '宁波集盒MR.BOX', type: changzhu, top: topType.type4, value: 19467 },
  { region: 'AGToys漫玩', type: changzhu, top: topType.type5, value: 31945 },
  { region: 'SFC上影影城(宁波店)', type: changzhu, top: topType.type5, value: 31152 },
  { region: '罗蒙环球乐园', type: changzhu, top: topType.type5, value: 30056 },
  { region: '乐酷KTV(宏泰广场)', type: changzhu, top: topType.type5, value: 27099 },
  { region: '阿正点播影院(城隍庙店)', type: changzhu, top: topType.type5, value: 18390 },
  { region: '北极王国冰雪世界(东部银泰城店)', type: changzhu, top: topType.type5, value: 16669 },
  { region: '中影国际影城(来福士店)', type: changzhu, top: topType.type5, value: 16309 },
  { region: '魅KTV(宁波高新宝龙广场店)', type: changzhu, top: topType.type5, value: 16014 },
  { region: '可可天空农场(东部新城银泰城店)', type: changzhu, top: topType.type5, value: 15875 },
  { region: 'TZ House音乐现场(宁波来福士店)', type: changzhu, top: topType.type5, value: 15087 },
  { region: '百老汇影城(印象城)', type: changzhu, top: topType.type5, value: 14916 },
  { region: '天伦·极度沸点KTV(朝晖路店)', type: changzhu, top: topType.type5, value: 13221 },
  { region: '涌上·音悦汇KTV(开明街店)', type: changzhu, top: topType.type5, value: 13169 },
  { region: '宁波恒鼎国际商务会所', type: changzhu, top: topType.type5, value: 12398 },
  { region: '宁波大光明主题影院(桑田路店)', type: changzhu, top: topType.type5, value: 12390 },
  { region: '自由人影城(宁波亚细亚CINITY店)', type: changzhu, top: topType.type5, value: 11950 },
  { region: '宁波大剧院', type: changzhu, top: topType.type5, value: 11923 },
  { region: '四合网苑(东柳店)', type: changzhu, top: topType.type5, value: 11281 },
  { region: 'Me land(东部新城银泰店)', type: changzhu, top: topType.type5, value: 11100 },
  { region: '江东一页时尚KTV', type: changzhu, top: topType.type5, value: 11002 }
]

export const custMark = [
  {
    key: 'radius1',
    list: ['授信', '未授信']
  },
  {
    key: 'radius2',
    list: ['有房', '无房']
  },
  {
    key: 'radius3',
    list: ['有车', '无车']
  },
  {
    key: 'radius4',
    list: ['男', '女']
  },
  {
    key: 'radius5',
    list: ['已婚', '未婚']
  },
  {
    key: 'radius6',
    list: ['有子女', '无子女']
  }
]
